# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98b145db9ddc0a8027768906e79c146c9157725818fa81b2f891d03773bf582b100c8b0c60925fff0e4b8e12040764a480a4d0d165be8e63fcf30cda27785603

test:
  secret_key_base: 74dfc5f8a497d1349c78540ee6cc9507890374286989bdaf6014864ccbb625c74e6b2e5a78dcad2ee4d80547e0d1ee0ee11bdaaa2bd0706f69c562ebc52c28fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
